# Generated by Django 5.1.7 on 2025-04-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='container_weight_at_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
